name: Production Deploy for Sagat APP

on:
  workflow_dispatch:

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Vercel CLI
        run: bun add --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }} --yes --environment=production

      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --target=production

      - name: Deploy to Vercel
        uses: iotaledger/deploy-to-vercel-action@9c73fe8ff3eb32d6ba30d623ac1b0c5708a25bb7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREBUILT: true
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          DELETE_EXISTING_COMMENT: true
          VERCEL_TARGET: production
